# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: error
  logs:
    custom_components.gce_xdisplay_v2: debug

cover:
  - platform: template
    covers:
      volet_salon:
        device_class: shutter
        friendly_name: "Volet Salon"
        value_template: "{{ is_state('media_player.cuisine', 'idle') }}"
        open_cover:
          action: automation.reload
        close_cover:
          action: automation.reload
        stop_cover:
          action: automation.reload

template:
  - sensor:
      - name: "Conso elec"
        unique_id: "conso_elec"
        unit_of_measurement: "Wh"
        device_class: energy
        state_class: total
        state: "{{ as_timestamp(now()) | int }}"
